name: "Use poetry to build package and run multiple tests"

on: [ push, pull_request ]

jobs:
    build_wheels_with_poetry:
        name: Build poetry packages on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]
                include:
                    -   os: ubuntu-latest
                        path: ~/.cache/pip
                    -   os: macos-latest
                        path: ~/Library/Caches/pip
                    -   os: windows-latest
                        path: ~\AppData\Local\pip\Cache
                python-version: [ 3.6, 3.7, 3.8, 3.9, '3.10' ]

        steps:
            -   uses: actions/checkout@v2

            -   uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install Poetry
                uses: snok/install-poetry@v1
                with:
                    virtualenvs-create: true
                    virtualenvs-in-project: true
#            -   name: Clear corrupted cache
#                run: poetry cache clear pypi --all --no-interaction
#                if: ${{ matrix.os == 'ubuntu-latest' }} # Clear Linux cache
            -   name: Load cached venv
                id: cached-pip-wheels
                uses: actions/cache@v2
                if: ${{ matrix.os != 'ubuntu-latest' }} # Linux cache seems to be corrupted
                with:
                    path: ~/.cache
                    key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
            -   name: Install dependencies
                run: |
                    poetry update
                    poetry install --no-interaction --no-root
            -   name: Install Package
                run: poetry install --no-interaction
            -   name: Build Package
                run: poetry build
            -   name: Run Bandit
                run: poetry run bandit -r pyprojectify/ -c .bandit.yml
            -   name: Run Type Checker
                run: |
                    poetry run pip install types-setuptools
                    poetry run pip install types-toml
                    poetry run mypy --strict --ignore-missing-imports --show-error-codes pyprojectify/
            -   name: Run Pytest
                run: poetry run pytest --cov=./pyprojectify/
            -   name: Upload coverage artifacts to codecov
                run: poetry run codecov --token=secrets.CODECOV_API_TOKEN
                if: ${{ matrix.python-version != '3.10' }} # codecov is not yet compatible with python 3.10.0
